### ISSUE TITLE
Class name is too generic.

### ISSUE THREAD

**Issue by dantman** [hafriedlander/php-peg#12]
The class name 'Parser' is far too generic. This is a library rather than a host system so it should avoid generic words.
For example, if I wanted to use this inside of a MediaWiki extension I could not use it as-is. Since it would conflict with MediaWiki's Parser class.

**Comment by hafriedlander** [comment]
Thanks to @ju1ius php-peg is now namespaced and PSR-0 compliant, so this shouldn't be an issue any more.
